name: my_quiz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_core: ^2.19.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  lottie: ^2.7.0
  riverpod_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  fake_cloud_firestore: ^2.4.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/animation/BouncingSquare.json
  fonts:
    - family: Zen Maru Gothic
      fonts:
        - asset: assets/fonts/ZenMaruGothic-Regular.ttf
        - asset: assets/fonts/ZenMaruGothic-Light.ttf
          weight: 100 
        - asset: assets/fonts/ZenMaruGothic-Bold.ttf
          weight: 700

analyzer:
  plugins:
    - custom_lint
    - riverpod_lint
