name: push

on:
  push:
    branches:
      - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        uses: invertase/github-action-dart-analyzer@v2.0.0
